version: '3.8'

services:
  nextjs:
    container_name: simple-travel-app
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    ports:
      - "${PORT:-3000}:3000"
    environment:
      NODE_ENV: ${NODE_ENV}
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
      PORT: ${PORT}
      HOSTNAME: ${HOSTNAME}
    restart: unless-stopped
    env_file:
      - .env.production
    # volumes:
    #   - .:/app          # ✅ hostdagi kodni container ichiga mount qiladi
    #   - /app/node_modules  # node_modules container ichida qoladi  
    healthcheck:
      test: [ "CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:${PORT}/" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
