version: '3.8'

services:
  nextjs:
    container_name: simple-travel-app-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
        NEXT_PUBLIC_IMAGE_API_HOST: ${NEXT_PUBLIC_IMAGE_API_HOST}
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
      NEXT_PUBLIC_IMAGE_API_HOST: ${NEXT_PUBLIC_IMAGE_API_HOST}
    volumes:
      - ./src:/app/src
      - ./pages:/app/pages
      - /app/node_modules

    restart: unless-stopped
