import Kuba from '@/assets/Kuba.jpg';
import OAE from '@/assets/OAE.jpg';
import ShriLanka from '@/assets/ShriLanka.jpg';
import Tailand from '@/assets/Tailand.jpg';
import Turk from '@/assets/Turk.jpg';
import { StaticImageData } from 'next/image';

interface FavouriteItem {
  name: string;
  rating: number;
  price: string;
  desc: string;
  img: StaticImageData;
  popular?: boolean;
  visa?: boolean;
}

export const dataFavourite: FavouriteItem[] = [
  //   {
  //     name: 'Таиланд',
  //     rating: 4.5,
  //     price: 'от 12 450 000 сум',
  //     desc: 'ОАЭ, Шарджа',
  //     img: Tailand,
  //     popular: true,
  //     visa: true,
  //   },
  //   {
  //     name: 'Куба',
  //     rating: 4,
  //     price: 'от 12 450 000 сум',
  //     desc: 'ОАЭ, Шарджа',
  //     img: Kuba,
  //     visa: true,
  //     popular: false,
  //   },
  //   {
  //     name: 'Турция',
  //     rating: 3,
  //     price: 'от 12 450 000 сум',
  //     desc: 'ОАЭ, Шарджа',
  //     img: Turk,
  //     popular: false,
  //     visa: true,
  //   },
  //   {
  //     name: 'ОАЭ',
  //     rating: 2,
  //     visa: true,
  //     price: 'от 12 450 000 сум',
  //     desc: 'ОАЭ, Шарджа',
  //     img: OAE,
  //     popular: true,
  //   },
  //   {
  //     name: 'Шри-Ланка',
  //     price: 'от 12 450 000 сум',
  //     visa: true,
  //     rating: 1,
  //     desc: 'ОАЭ, Шарджа',
  //     img: ShriLanka,
  //     popular: true,
  //   },
  //   {
  //     name: 'Таиланд',
  //     rating: 4.5,
  //     price: 'от 12 450 000 сум',
  //     desc: 'ОАЭ, Шарджа',
  //     img: Tailand,
  //     popular: true,
  //     visa: true,
  //   },
  //   {
  //     name: 'Куба',
  //     rating: 4,
  //     price: 'от 12 450 000 сум',
  //     desc: 'ОАЭ, Шарджа',
  //     img: Kuba,
  //     visa: true,
  //     popular: false,
  //   },
  //   {
  //     name: 'Турция',
  //     rating: 3,
  //     price: 'от 12 450 000 сум',
  //     desc: 'ОАЭ, Шарджа',
  //     img: Turk,
  //     popular: false,
  //     visa: true,
  //   },
  //   {
  //     name: 'ОАЭ',
  //     rating: 2,
  //     visa: true,
  //     price: 'от 12 450 000 сум',
  //     desc: 'ОАЭ, Шарджа',
  //     img: OAE,
  //     popular: true,
  //   },
  //   {
  //     name: 'Шри-Ланка',
  //     price: 'от 12 450 000 сум',
  //     visa: true,
  //     rating: 1,
  //     desc: 'ОАЭ, Шарджа',
  //     img: ShriLanka,
  //     popular: true,
  //   },
  //   {
  //     name: 'Таиланд',
  //     rating: 4.5,
  //     price: 'от 12 450 000 сум',
  //     desc: 'ОАЭ, Шарджа',
  //     img: Tailand,
  //     popular: true,
  //     visa: true,
  //   },
  //   {
  //     name: 'Куба',
  //     rating: 4,
  //     price: 'от 12 450 000 сум',
  //     desc: 'ОАЭ, Шарджа',
  //     img: Kuba,
  //     visa: true,
  //     popular: false,
  //   },
  //   {
  //     name: 'Турция',
  //     rating: 3,
  //     price: 'от 12 450 000 сум',
  //     desc: 'ОАЭ, Шарджа',
  //     img: Turk,
  //     popular: false,
  //     visa: true,
  //   },
  //   {
  //     name: 'ОАЭ',
  //     rating: 2,
  //     visa: true,
  //     price: 'от 12 450 000 сум',
  //     desc: 'ОАЭ, Шарджа',
  //     img: OAE,
  //     popular: true,
  //   },
  //   {
  //     name: 'Шри-Ланка',
  //     price: 'от 12 450 000 сум',
  //     visa: true,
  //     rating: 1,
  //     desc: 'ОАЭ, Шарджа',
  //     img: ShriLanka,
  //     popular: true,
  //   },
  //   {
  //     name: 'Таиланд',
  //     rating: 4.5,
  //     price: 'от 12 450 000 сум',
  //     desc: 'ОАЭ, Шарджа',
  //     img: Tailand,
  //     popular: true,
  //     visa: true,
  //   },
  //   {
  //     name: 'Куба',
  //     rating: 4,
  //     price: 'от 12 450 000 сум',
  //     desc: 'ОАЭ, Шарджа',
  //     img: Kuba,
  //     visa: true,
  //     popular: false,
  //   },
  //   {
  //     name: 'Турция',
  //     rating: 3,
  //     price: 'от 12 450 000 сум',
  //     desc: 'ОАЭ, Шарджа',
  //     img: Turk,
  //     popular: false,
  //     visa: true,
  //   },
  //   {
  //     name: 'ОАЭ',
  //     rating: 2,
  //     visa: true,
  //     price: 'от 12 450 000 сум',
  //     desc: 'ОАЭ, Шарджа',
  //     img: OAE,
  //     popular: true,
  //   },
  //   {
  //     name: 'Шри-Ланка',
  //     price: 'от 12 450 000 сум',
  //     visa: true,
  //     rating: 1,
  //     desc: 'ОАЭ, Шарджа',
  //     img: ShriLanka,
  //     popular: true,
  //   },
  //   {
  //     name: 'Таиланд',
  //     rating: 4.5,
  //     price: 'от 12 450 000 сум',
  //     desc: 'ОАЭ, Шарджа',
  //     img: Tailand,
  //     popular: true,
  //     visa: true,
  //   },
  //   {
  //     name: 'Куба',
  //     rating: 4,
  //     price: 'от 12 450 000 сум',
  //     desc: 'ОАЭ, Шарджа',
  //     img: Kuba,
  //     visa: true,
  //     popular: false,
  //   },
];

export const dataHotTours: FavouriteItem[] = [
  {
    name: 'Pullman Sharjah',
    rating: 3,
    popular: true,
    desc: 'ОАЭ, Шарджа',
    price: 'от 12 450 000 сум',
    visa: true,
    img: Turk,
  },
  {
    name: 'Таиланд',
    visa: true,
    popular: false,
    price: 'от 12 450 000 сум',
    rating: 3,
    desc: 'ОАЭ, Шарджа',
    img: Tailand,
  },
  {
    name: 'Шри-Ланка',
    price: 'от 12 450 000 сум',
    visa: true,
    rating: 1,
    desc: 'ОАЭ, Шарджа',
    img: ShriLanka,
    popular: true,
  },
  {
    name: 'ОАЭ',
    rating: 2,
    visa: true,
    price: 'от 12 450 000 сум',
    desc: 'ОАЭ, Шарджа',
    img: OAE,
    popular: true,
  },
  {
    name: 'Куба',
    rating: 4,
    price: 'от 12 450 000 сум',
    desc: 'ОАЭ, Шарджа',
    img: Kuba,
    visa: true,
    popular: false,
  },
  {
    name: 'Турция',
    rating: 3,
    price: 'от 12 450 000 сум',
    desc: 'ОАЭ, Шарджа',
    img: Turk,
    popular: false,
    visa: true,
  },
  {
    name: 'Таиланд',
    rating: 4.5,
    price: 'от 12 450 000 сум',
    desc: 'ОАЭ, Шарджа',
    img: Tailand,
    popular: true,
    visa: true,
  },
];
